### ISSUE TITLE
A TypeError is raised when the sum of values is 0

### ISSUE THREAD

**Issue by stillhart** [piotrmurach/tty-pie#3]
### Describe the problem

The pie rendering fails when the sum of values in a pie is equal to 0.

### Steps to reproduce the problem

```ruby
TTY::Pie.new(data: [{ name: "DOGE", value: 0 }], radius: 2).render
=> TypeError: no implicit conversion from nil to integer
```

As a possible spec:
```ruby
  it "renders an empty pie chart when all values are 0 " do
    data = [
      { name: "BTC", value: 0 },
      { name: "BCH", value: 0 },
      { name: "LTC", value: 0 }
    ]
    pie = TTY::Pie.new(data: data, radius: 2)

    output = pie.render

    expect(output).to eq([
       "            • BTC 0%\n",
       "         ",
       "            • BCH 0%\n",
       "         ",
       "            • LTC 0%\n"
    ].join)
  end
```

Which results in the following failure
```
  1) TTY::Pie#render renders an empty pie chart when all values are 0
     Failure/Error: item = items[select_data_item(angle, angles)]

     TypeError:
       no implicit conversion from nil to integer
     # ./lib/tty/pie.rb:143:in `block (2 levels) in render'
     # ./lib/tty/pie.rb:141:in `each'
     # ./lib/tty/pie.rb:141:in `block in render'
     # ./lib/tty/pie.rb:136:in `each'
     # ./lib/tty/pie.rb:136:in `render'
     # ./spec/unit/render_spec.rb:83:in `block (2 levels) in <top (required)>'
```

### Actual behaviour

An exception was raised

### Expected behaviour

Either an empty pie or at least an empty string. 

### Describe your environment

* OS version: RHEL 7.9
* Ruby version: 3.0.1
* TTY::Pie version: 0.4.0 & master

### Sorry

Sorry, somehow I am having very unusal trouble to push a merge request which at least contains the mentioned spec to reproduce. Therefore I won't do this (now).

### Thanks
Thank you very much for all your tty efforts. I love them all.

**Comment by piotrmurach** [comment]
Thank you for reporting this issue! Nicely spotted edge case.

**Comment by piotrmurach** [comment]
@stillhart This is fixed now and ready for checking when you have a minute. I'll make a release shortly.
